export { Queries } from './fragments'
export { client } from './components/ApolloClient'
export { Covid19ApiConfig } from './configuration/Covid19ApiConfig'
export * as Types from './types/types'
export { ApiConfig } from './configuration/ApiConfig'
